language: php

php:
  - 7.3
  - 7.4

before_script:
  - composer install

script:
  - pyrus install http://phptal.org/latest.tar.gz
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
  - phpcs --standard=PSR12 src
  - phpunit --coverage-text --bootstrap tests/bootstrap.php tests/

notifications:
  email: false
