language: php

php:
  - 7.3
  - 7.4

before_script:
  - composer install

script:
  - php vendor/bin/phpcs --standard=PSR12 src
  - php vendor/bin/phpstan analyse
  - php vendor/bin/psalm
  - php vendor/bin/phpunit

notifications:
  email: false
